Add missing deps for simd_armv8a
Building for armv8 fails with error:

ERROR: .../bazel/external/jpeg/BUILD:288:1: undeclared inclusion(s) in rule '@jpeg//:simd_armv8a':
this rule is missing dependency declarations for the following files included by 'external/jpeg/simd/jsimd_arm64.c':
'.../bazel/external/jpeg/jpegint.h'
'.../bazel/external/jpeg/jerror.h'